sintes = ['coast 0_coast', '000', '4ms', 'avp a-v-p_synth', 'acces', 'access', 'digitakt elektron','voix la-voix-du-luthier', 'luthier la-voix-du-luthier', 
'oktatrak elektron','analog elektron','heat elektron','rythm elektron','digitone elektron','keys elektron','cycles elektron','samples elektron','acidlab', 'akai',
'mpc akai','alembic', 'alesis', 'allen allen_&_heath', 'analogaudio1', 'analogue solutions', 'analogue systems', 'arp', 'arturia', 'asm ashun_soundmachines', 
'atomo atomo_synth', 'damage audio_damage', 'audiophile audiophile_circuits', 'axoloty', 'balaguer', 'baloran', 'bastl bastl_instruments', 'befaco', 'behringer', 
'beringer', 'bheringer', 'bitbox', 'black corporation', 'boss', 'bubblesound instruments', 'buchla', 'casio', 'charlie lab', 'charvel', 'chronograf', 'circuit abbey', 'clavia', 
'club knobs', 'corsynth', 'cre8audio', 'crumar', 'custom made', 'cyclone', 'cyclone', 'dave jones', 'dave smith', 
'dave smith instruments', 'deepmind', 'delptronics', 'delta music', 'denon dj', 'dexibell', 'dexibell', 'digitack', 'doepfer', 
'dreadbox', 'dubreq', 'dynacord', 'e mu', 'e-mu', 'e-mu', 'e:m:c', 'elby designs', 'electribe', 'electronic music laboratories (eml)', 
'electrovoice', 'elektron', 'elka', 'emc', 'emu', 'endorphin.es', 'endorphines', 'ensoniq', 'eowave', 'epiphone', 'erica synth', 'erica synths', 
'ernie ball music man', 'esp ltd', 'eurorack', 'eventide', 'evh', 'evolver', 'exodus digital', 'farfisa', 'fender', 'fishman', 'fodera', 'formanta', 
'frap tool', 'frequency central', 'fretlight', 'friedman', 'future retro', 'futuresonus', 'gator', 'gemini', 'generalmusic', 'gibson', 'godin', 'gotharman', 
'graph tech', 'gretsch', 'guild', 'hammond', 'hartmann', 'hexinverter', 'hinton instruments', 'hofner', 'hypersynth', 'ibanez', 'ik', 'instruo', 'iomega', 
'isla', 'jackson', 'jaspers', 'john bowen synth design', 'jomox', 'kawai', 'kenton', 'ketron', 'kilpatrick audio', 'knobula', "motif-rack",
'koma elektronik', 'komplete', 'korg', 'kramer', 'kurzweil', 'kurzweil', 'lakland', 'line 6', 'linn electronics', 'livid', 'logan electronics', 'm-audio', 
'macbeth studio systems', 'make', 'malekko', 'manikin electronic', 'maschine', 'mellotron', 'mfb', 'micro modular', 'miditech', 
'models', 'modor', 'modular', 'modulus', 'monome', 'moog', 'mpc', 'mpc', 'mutable instruments', 'mutant', 'native instruments', 'neutron', 'noise engineering', 
'nord', 'nord electro', 'nord lead 2 rack', 'nord lead 3', 'nord lead 3', 'nord lead 4', 'nord micro modular', 'nord modular', 'nord rack', 'nord stage', 
'nord wave', 'novation', 'numark', 'oberheim', 'octatrack', 'orthogonal devices', 'paratek', 'pearl', 'peavey', 'pioneer dj', 'pittsburgh', 'pittsburgh modular', 
'polyend', 'polygraf', 'ppg (palm products gmbh)', 'prs', 'qu bit', 'qu-bit', 'qu-bit electronix', 'quasimidi', 'qubit', 'quiklok', 'radikal technologies', 
'rhodes', 'rickenbacker', 'roland', 'roli', 'sanson', 'schecter', 'sensel', 'sequencial', 'sequential circuits', 'sequentix', 'shakmat', 'simmons', 'soma', 'sonicware', 'special waves', 'spector', 'spectral audio', 'sputnik', 'squarp instruments', 
'squier', 'ssff', 'stanton', 'steinberger', 'sterling', 'strymon', 'studio electronics', 'synamodec', 'synthesis technology', "clattersmachines","clatters",
'synthrotek', 'synthstrom', 'synthstrom', 'synthtech','swissonic', 'tascam', 'taylor', 'technos', 'teenage', 'teenage engineering', 'tiptop', 'tiptop audio', "antumbra","cara",
'traveler guitar', 'udo audio', 'uno synth ', 'vermona', 'vermona', 'virus', 'viscount', 'volca', 'vox', 'waldorf', 'warwick', 'washburn', 'waves grendel', 
'wersi', 'wersi music', 'winter modular', 'wmd', 'wmd / ssf', 'wurlitzer', 'yamaha', 'yocto', 'zeppelin design labs', 'zoom','1010 music', '2hp', '4ms', 'acid rain technology', 
'acl', 'addac system', 'after later audio', 'aion modular', 'ajh synth', 'cosmos soma', 'divina soma', 'enner soma', 'ether soma', 'flux soma', 'illuminator soma', "ikarie",
'lyra-8 soma', 'lyra8-fx soma', 'metaconformer soma', 'ornament-8 soma', 'pulsar-23 soma', 'qo soma', 'reflex soma', 'roat soma', 'terra soma', 'the pipe soma',
'alm busy circuits', 'alright devices', 'analogue solutions', 'bastl instruments', 'befaco', 'blackhole cases', 'blue lantern', 'boredbrain music', "midiplus",
'bubblesound', 'buchla', 'cosmotronic', 'cre8audio', 'divkid', 'dnipro modular', 'doepfer', 'dreadbox', 'e-rm','LinnDrum','Linn Electronics', 'electrosmith', 'emblematic systems', 
'empress effects', 'endorphin.es', 'eowave', 'erica synths', 'erogenous tones', 'eskatonic modular', 'eventide', 'five12', 'frap tools', 'future sound systems', 
'gieskes', 'grayscale', 'hexinverter', 'industrial music electronics','voix du luthier', 'instruo','error instruments','', 'io instruments', 'jomox', 'joranalogue', 'klavis', 
'koma elektronik', 'l-1', 'lmntl', 'low-gain electronics', 'lzx industries', 'make noise','eloquencer', 'malekko', 'manhattan analog', 'meng qi', "nerdseq",
'michigan synth works', 'modbap modular', 'moog', 'mordax', 'mosaic', 'mrseri', 'mutable instruments', 'nano modules', 'noise engineering', 'dave-smith-instruments','dave','dave-smith'
'patching panda', 'percussa', 'pittsburgh modular', 'plankton electronics','oxi', 'poly effects', 'qu-bit electronix', 'random source', 'ritual electronics', "studio-electronics",
'rossum', 'schlappi engineering', 'shakmat modular', 'soundforce', 'soundmachines', 'squarp', 'steady state fate', 'neuzeit','strymon', 'studio electronics', 
'supercritical', 'synthesis technology', 'system 80', 'tall dog electronics', 'tasty chips', 'tenderfoot electronics', 'tesseract modular', 'tiptop audio', "flightcase",
'trogotronic', 'tubbutec', 'u-he', 'verbos electronics',"viscount", 'vermona', 'voicas', 'vpme.de', 'winter modular', 'wmd', 'worng electronics', 'xaoc devices', "asm",
'xor electronics', 'zlob modular',"ASM","Elektron","Moog","Teenage Engineering","Korg","Novation","Modal Electronics","drumatix","klavis","antimatter" , "mimetic-digitalis", 
"Black Corporation","Roland","Arturia","Critter & Guitari","Polyend","UDO","Waldorf","Nord","Yamaha","Vermona","Crumar","JMT Synth","Modor","qu-bit","qubitelectronix",
"Studio Electronics","Trogotronic","Gieskes","Akai","Dreadbox","Herbs and Stones","IK Multimedia","Tasty Chips","Buchla","Soundmachines","mordax","nektar","dreadbox",
"Access","Grp","Analogue Solutions","The Division Department","Norand","Jomox","Sonicware","Radikal Technologies","Playtime Engineering",
"1010 Music","Fred's Lab","Kilpatrick Audio","Eowave","Electrosmith","Meng Qi","Studiologic","Suzuki","Nonlinear Labs","Dato","Artiphon","evo","evo audio"
"Malekko Heavy Industry","Kodamo","Hikari Instruments","Manikin Electronic","Second Sound","Arturia","Squarp","Polyend","Novation","Akai","dexibell",
"Roger Linn Design","Conductive Labs","Native Instruments","Faderfox","Sensel","Roland","Keith McMillen","Pioneer","E-RM","Expressive E","Korg",
"M-Audio","Alesis","JouÃ©","Soundforce","Yamaha","Genki","Erica Synths","Make Noise","Doepfer","Elektron","Moog","organelle",
"Teenage Engineering","1010 Music","Expert Sleepers","BASTL Instruments","Kenton","Circuit Happy","MOTU","MIDI Solutions","Solid State Logic",
"Nord","Koma Elektronik","Random Source","Eowave","preenfm2","Zoom","Crumar","Electro-Harmonix","Grp","Michigan Synth Works",
"Analogue Solutions","Knas","iConnectivity","Soundmachines","Eurodesk-Z","Presonus","Torso Electronics","IK Multimedia","ESI Audiotechnik",
"Low-Gain Electronics","Artiphon","Instruments of Things","Apogee","SND","Moffenzeef","CME","Embodme","wmd","wmdevices","leslie",
"Tech 21","Snyderphonics","Tricks Magic Shop","Strymon","Vermona","OTO Machines","Dreadbox","Chase Bliss Audio","Boss","GFI","Meris",
"Eventide","SOMA Laboratory","Echo Fix","Fairfield Circuitry","Universal Audio","Gamechanger Audio","EarthQuaker Devices","Death By Audio","mu","zips","zip"
"Sherman","Electro-Harmonix","Old Blood Noise Endeavors","Knas","Red Panda","Kemper","DigiTech","JAM Pedals","Splinter",
"Erica Synths","Elektron","WMD","1010 Music","Roland","Korg","Poly Effects","Jomox","Thermionic Culture","Warm Audio","varigate",
"Zoom","Boredbrain Music","Meng Qi","Electrosmith","Benidub","BAE","Trogotronic","MIDI Solutions","Plankton Electronics","Vongon",
"ART","Hungry Robot","Walrus Audio","Enjoy Electronics","CIOKS","TK Audio","Source Audio","API","Voodoo Lab","rml","iomega",
"FMR Audio","JHS Pedals","MOD Devices","Cooper FX","Finegear","Ezhi & Aka","Truetone","LastGasp Art Laboratories","Origin Effects","artiphon",
"Rainger FX","Line 6","PedalTrain","Dr. Scientist","Elta Music","Keeley","Recovery","Glou-Glou","Retro Mechanical Labs","Electro-Faustus",
"Animal Factory","Hologram","Caroline Guitar Company","MXR","Second Sound","Xotic","Dunlop","Adventure Audio","ISP Technologies",
"Industrialectric","Tech 21","Collision Devices","Orgeldream","Universal Audio","API","Solid State Logic","Rupert Neve Designs","Shure","MOTU",
"Warm Audio","Focusrite","Vermona","Focal","Neumann","Roland","Thermionic Culture","Arturia","Zoom","Presonus","Adam","ART","Yamaha",
"TASCAM","Furman","Antelope Audio","Dangerous Music","Pioneer","Echo Fix","Native Instruments","Eventide","Allen & Heath",
"Meris","Sherman","dbx","BAE","Maag Audio","Empirical Labs","Avantone Pro","iConnectivity","Mackie","Audient","beyerdynamic","TK Audio",
"IK Multimedia","Black Lion Audio","RME","Keith McMillen","Golden Age Project","Audio-Technica","Fredenstein","A-Designs","Rosson Audio",
"Daking","Looptrotter","Rode","Prism Sound","Samson","Cranborne Audio","ESI Audiotechnik","Elysia","HEDD","FMR Audio","Heritage Audio",
"Avedis Audio","Sennheiser","Lindell Audio","Blue Microphones","Apogee","Recovery","M-Audio","Zeppelin Design Labs","KRK","AKG",
"Cloud Microphones","Steinberg","Alesis","Dynaudio","Austrian Audio","Auralex","IsoAcoustics","Aston Microphones","Auratone","sE Electronics","SE Electronics",
"Tech 21","Lauten Audio","Cascade Microphones","Soundrise","Pioneer","Allen & Heath","Pro-Ject","PLAYdifferently","U-Turn Audio","Audio-Technica",
"Thorens","Audioengine","Technics","Rane","AKG","Music Hall","Native Instruments","Numark","Sennheiser","Jesse Dean Designs","Ortofon",
"Rosson Audio","MWM","Gator","IK Multimedia","ART","Yamaha","Ultimate Support","RME","Roland","KRK","Austrian Audio","Shure","Odyssey",
"Teenage Engineering","Denon","Record Props","Presonus","Hosa","Hosa","Mogami ","Roland ","Voodoo Lab ","CIOKS ","LMNTL ","Warm Audio "
"Teenage Engineering ","myVolts ","Gator ","Truetone ","Strymon ","Eurodesk-Z","Furman","Elektron","Tiptop Audio","Retrokits","4MS","EBS",
"Pomona Electronics","Modbang","Intellijel Designs","Plankton Electronics","Radial Engineering","1010 Music","Native Instruments",
"Expert Sleepers","Buchla","iConnectivity","Modbap Modular","Boredbrain Music","Make Noise","Korg","Moog ","Rode ","Shure ",
"LabLab Audio ","Zoom ","Doepfer ","Koma Elektronik ","ADDAC System ","Frap Tools ","Endorphin.es ","ART s","Yamaha ","Walrus Audio",
"ALM Busy Circuits ","Analogue Solutions ","Trogotronic ","Befaco ","Boss ","Soundmachines ","LZX Industries ","Cyclone Analogic ",
"M-Audio ","E-RM ","Pulp Logic ","Electro-Harmonix ","ESI Audiotechnik ","Eskatonic Modular ","Eventide ","Instruo ","Keith McMillen","noise-engineering",
"Malekko Heavy Industry ","Dunlop"]